package pg.ui.exception;

/**Created by Gawa 2017-10-07*/
public enum UIError {
    LOAD_BUNDLE,
    LOAD_PROPERTIES,
    SAVE_PROPERTIES,
    NULL_ARGUMENT,
    NO_ARGUMENTS,
    PREPARATION,
    NULL_ERROR_CODE,
    BUTTON_IMG,
    DESTINATION_NOT_CREATED,
    LAUNCH_PROGRAM,
    ARGUMENT_WRONG_VALUE
}
